# Лабораторна робота №6(7) - Побудова повнозв'язної нейронної мережі для розпізнавання шрифтів за наданим датасетом

## 1) Завантаження даних
Я обрала такі шрифти для побудови мережі: Arial, Book, Cambria, Italic, Lucida, Monotxt, Ocrb, Segoe, Times.

Вони містяться у архіві, доданому до завдання.

In [9]:
from google.colab import files
import zipfile
import os
import pandas as pd
import glob
import shutil  # Import shutil for removing directories

# Step 1: Define the dataset directory and clear it if it exists
dataset_dir = '/content/dataset/'

# Clear the dataset directory
if os.path.exists(dataset_dir):
    shutil.rmtree(dataset_dir)  # Remove the entire directory and its contents

# Create the dataset directory again
os.makedirs(dataset_dir, exist_ok=True)

In [10]:
# Step 2: Upload the zipped folder
uploaded = files.upload()

Saving fonts.zip to fonts.zip


In [11]:
# Step 3: Unzip the folder
for filename in uploaded.keys():
    if filename.endswith('.zip'):
        zip_ref = zipfile.ZipFile(filename, 'r')
        zip_ref.extractall(dataset_dir)  # Extract to /content/dataset folder
        zip_ref.close()

# Step 4: List all CSV files in the dataset directory and its subdirectories
csv_files = glob.glob(f'{dataset_dir}/**/*.csv', recursive=True)  # Search recursively
print(f"Found {len(csv_files)} CSV files.")

# Step 5: Merge all CSV files into a single DataFrame
dataframes = []
for csv_file in csv_files:
    print(f"Loading {csv_file}...")
    df = pd.read_csv(csv_file)  # Load each CSV file into a DataFrame
    dataframes.append(df)

Found 9 CSV files.
Loading /content/dataset/fonts/OCRB.csv...
Loading /content/dataset/fonts/BOOK.csv...
Loading /content/dataset/fonts/CAMBRIA.csv...
Loading /content/dataset/fonts/SEGOE.csv...
Loading /content/dataset/fonts/TIMES.csv...
Loading /content/dataset/fonts/MONOTXT.csv...
Loading /content/dataset/fonts/ITALIC.csv...
Loading /content/dataset/fonts/LUCIDA.csv...
Loading /content/dataset/fonts/ARIAL.csv...


In [12]:
# Step 6: Check if dataframes list is not empty before concatenating
if dataframes:
    merged_df = pd.concat(dataframes, ignore_index=True)

    # Step 7: Save the merged DataFrame to a CSV file
    merged_df.to_csv(os.path.join(dataset_dir, 'merged_fonts.csv'), index=False)
    print("Merged dataset saved as 'merged_fonts.csv'")
else:
    print("No CSV files were found to merge.")


Merged dataset saved as 'merged_fonts.csv'


In [13]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244971 entries, 0 to 244970
Columns: 412 entries, font to r19c19
dtypes: float64(2), int64(408), object(2)
memory usage: 770.0+ MB


In [14]:
merged_df.head()

font fontVariant  m_label  strength  italic  orientation  m_top  m_left  \
0  OCRB     scanned       60       0.4       0          0.0      0       0   
1  OCRB     scanned       60       0.4       0          0.0      0       0   
2  OCRB     scanned       40       0.4       0          0.0      0       0   
3  OCRB     scanned       43       0.4       0          0.0      0       0   
4  OCRB     scanned       55       0.4       0          0.0      0       0   

   originalH  originalW  ...  r19c10  r19c11  r19c12  r19c13  r19c14  r19c15  \
0         12          9  ...      36     117     127     103      92     116   
1         12         11  ...     105     168     175     194     208     225   
2         45         14  ...      29     158     255     255     235     162   
3         38         19  ...     185     199     121      83       1       1   
4         16         10  ...       1       1       1       1       1       1   

   r19c16  r19c17  r19c18  r19c19  
0     146     158     202     202  
1     230     232     226     225  
2       1       1       1       1  
3       1       1       1       1  
4       1       1       1       1  

[5 rows x 412 columns]

In [15]:
merged_df.describe()

m_label       strength         italic  orientation  \
count  244971.000000  244971.000000  244971.000000     244971.0   
mean     5352.700369       0.486409       0.265595          0.0   
std     13637.614008       0.135854       0.441650          0.0   
min        33.000000       0.400000       0.000000          0.0   
25%        60.000000       0.400000       0.000000          0.0   
50%       219.000000       0.400000       0.000000          0.0   
75%      2664.000000       0.700000       1.000000          0.0   
max     65533.000000       0.700000       1.000000          0.0   

               m_top         m_left      originalH      originalW         h  \
count  244971.000000  244971.000000  244971.000000  244971.000000  244971.0   
mean       24.940091      13.362312      36.315462      28.277776      20.0   
std        23.606125      12.033925      17.167283      16.223439       0.0   
min         0.000000       0.000000       1.000000       1.000000      20.0   
25%         0.000000       0.000000      19.000000      16.000000      20.0   
50%        30.000000      20.000000      35.000000      24.000000      20.0   
75%        44.000000      23.000000      49.000000      38.000000      20.0   
max       107.000000      88.000000     100.000000     171.000000      20.0   

              w  ...         r19c10         r19c11         r19c12  \
count  244971.0  ...  244971.000000  244971.000000  244971.000000   
mean       20.0  ...     120.088864     114.293431     108.195974   
std         0.0  ...     112.921682     110.712530     107.805992   
min        20.0  ...       0.000000       0.000000       0.000000   
25%        20.0  ...       1.000000       1.000000       1.000000   
50%        20.0  ...     103.000000      89.000000      79.000000   
75%        20.0  ...     255.000000     255.000000     246.000000   
max        20.0  ...     255.000000     255.000000     255.000000   

              r19c13         r19c14         r19c15         r19c16  \
count  244971.000000  244971.000000  244971.000000  244971.000000   
mean      101.920370      94.909614      83.237028      74.009703   
std       107.038849     106.032971     102.984116     100.436821   
min         0.000000       0.000000       0.000000       0.000000   
25%         1.000000       1.000000       1.000000       1.000000   
50%        59.000000      34.000000       2.000000       1.000000   
75%       234.000000     216.000000     181.000000     155.000000   
max       255.000000     255.000000     255.000000     255.000000   

              r19c17         r19c18         r19c19  
count  244971.000000  244971.000000  244971.000000  
mean       64.123219      51.960224      41.418735  
std        96.270399      90.711603      82.321065  
min         0.000000       0.000000       0.000000  
25%         1.000000       1.000000       1.000000  
50%         1.000000       1.000000       1.000000  
75%       128.000000      59.000000      13.000000  
max       255.000000     255.000000     255.000000  

[8 rows x 410 columns]

## 2) Попередня підготовка

In [16]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# Step 1: Separate the target and features
X = merged_df.drop(columns=['font', 'fontVariant'])  # Drop both target and duplicate column
y = merged_df['font']  # Target column (font)

# Step 2: Define numerical attributes (all remaining features are numerical)
num_attribs = ['strength', 'italic', 'orientation', 'm_top', 'm_left', 'originalH', 'originalW'] + [f'r19c{i}' for i in range(10, 20)]

# Step 3: Create Pipelines for Numerical Features
# Numerical pipeline - imputing missing values and scaling
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),  # Fill missing values with median
    ('scaler', StandardScaler())  # Standardize features
])

# Step 4: Combine Pipelines using ColumnTransformer (since only numerical data, no categorical pipeline is needed)
full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs)
])

# Step 5: Fit and Transform the Features
X_prepared = full_pipeline.fit_transform(X)

# Step 6: One-Hot Encode the Target Variable (y)
y_onehot = OneHotEncoder(sparse_output=False)  # Set sparse_output=False to return a dense array
y_encoded = y_onehot.fit_transform(y.values.reshape(-1, 1))  # Reshape y for encoding

# Step 7: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_prepared, y_encoded, test_size=0.2, random_state=42)


In [17]:
X_train

array([[ 1.57221513,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527, -0.60137006,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527, -0.60137006,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       ...,
       [ 1.57221513,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527, -0.60137006,  0.        , ...,  0.9024265 ,
         0.33115761,  0.06779888]])

In [18]:
X_test

array([[ 1.57221513,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [ 1.57221513,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527, -0.60137006,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       ...,
       [-0.63604527,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [ 1.57221513, -0.60137006,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998],
       [-0.63604527,  1.66286961,  0.        , ..., -0.65568802,
        -0.56178401, -0.49098998]])

In [19]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [20]:
y_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

## 3) Побудова нейронної мережі

In [21]:
!pip install scikeras

from scikeras.wrappers import KerasClassifier

import numpy as np
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


# Step 1: Define a function to create the model with variable layers and neurons
def create_model(num_hidden_layers=1, num_neurons=128, optimizer='adam', dropout_rate=0.3):
    model = Sequential()

    # Input layer
    model.add(Dense(num_neurons, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dropout(dropout_rate))  # Dropout to prevent overfitting

    # Adding hidden layers based on num_hidden_layers
    for _ in range(num_hidden_layers - 1):
        model.add(Dense(num_neurons, activation='relu'))
        model.add(Dropout(dropout_rate))  # Dropout for each hidden layer

    # Output layer
    model.add(Dense(y_train.shape[1], activation='softmax'))  # Adjust this for multi-class classification
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

## 4) Підбір гаперпараметрів

In [ ]:
# Step 2: Wrap the model using KerasClassifier
model = KerasClassifier(build_fn=create_model, verbose=0, dropout_rate=0.3, num_hidden_layers=1, num_neurons=128)

In [23]:
# Step 3: Define the grid of hyperparameters to search
param_grid = {
    'num_hidden_layers': [2, 3],         # Experiment with 2 and 3 hidden layers
    'batch_size': [32, 64],              # Different batch sizes
    'epochs': [30, 40]                     # Number of epochs to train the model
}

In [24]:
# Step 4: Setup GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=2)  # Use 2-fold cross-validation

In [79]:
# Step 5: Fit GridSearchCV
grid_result = grid.fit(X_train, y_train)

# Step 6: Print the best parameters and score
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

# Get the results for all combinations
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, std, param in zip(means, stds, params):
    print(f"{mean} (+/- {std}) with: {param}")

/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,
/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Best: 0.8050628648405926 using {'batch_size': 64, 'epochs': 40, 'num_hidden_layers': 3}
0.7903314691594889 (+/- 0.0034187859737927484) with: {'batch_size': 32, 'epochs': 30, 'num_hidden_layers': 2}
0.796903702494183 (+/- 0.0009695064701800149) with: {'batch_size': 32, 'epochs': 30, 'num_hidden_layers': 3}
0.7926225660284933 (+/- 0.003403477976895164) with: {'batch_size': 32, 'epochs': 40, 'num_hidden_layers': 2}
0.7986181981467119 (+/- 0.0032555006735518477) with: {'batch_size': 32, 'epochs': 40, 'num_hidden_layers': 3}
0.7876270563742499 (+/- 0.004745479038249623) with: {'batch_size': 64, 'epochs': 30, 'num_hidden_layers': 2}
0.8021441400987877 (+/- 0.003056496713883361) with: {'batch_size': 64, 'epochs': 30, 'num_hidden_layers': 3}
0.7939135404335225 (+/- 0.00021431195656607116) with: {'batch_size': 64, 'epochs': 40, 'num_hidden_layers': 2}
0.8050628648405926 (+/- 0.005658856186471828) with: {'batch_size': 64, 'epochs': 40, 'num_hidden_layers': 3}


In [49]:
# Step 7: Retrieve the best parameters from grid search
#best_params = grid_result.best_params_
best_params = {
    'num_hidden_layers': 3,
    'batch_size': 64,
    'epochs': 40
}
print(f"Best Parameters: {best_params}")

# Step 8: Create a new model using the best parameters
best_model = create_model(
    num_hidden_layers=best_params['num_hidden_layers']
)

Best Parameters: {'num_hidden_layers': 3, 'batch_size': 64, 'epochs': 40}


In [50]:
# Step 9: Train the model with the training data
best_model.fit(X_train, y_train, batch_size=best_params['batch_size'], epochs=best_params['epochs'], verbose=1)

Epoch 1/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.6103 - loss: 1.3011
Epoch 2/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.7004 - loss: 0.9622
Epoch 3/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.7073 - loss: 0.9153
Epoch 4/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.7096 - loss: 0.9022
Epoch 5/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.7076 - loss: 0.8996
Epoch 6/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.7096 - loss: 0.8902
Epoch 7/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.7116 - loss: 0.8830
Epoch 8/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.7102 - loss: 0.8849
Epoch 9/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7106 - loss: 0.8816
Epoch 10/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.7120 - loss: 0.8753
Epoch 11/40
3063/3063 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.7112 - loss: 0.8762
Epoch 12/40
3063/3063 ━━━━━━

In [51]:
# Step 10: Evaluate the model on the test data
test_loss, test_accuracy = best_model.evaluate(X_test, y_test, verbose=1)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

1532/1532 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7388 - loss: 0.8147
Test Loss: 0.8151417970657349
Test Accuracy: 0.7384222745895386


In [52]:
# Step 11: Save the model
best_model.save('font_classification_model.keras')